# Generated by Django 3.2.13 on 2024-11-04 19:50

import backend.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateField()),
                ('payment_method', models.CharField(max_length=20)),
                ('payment_status', models.CharField(default='Pending', max_length=20)),
            ],
            options={
                'db_table': 'Fees',
            },
        ),
        migrations.CreateModel(
            name='JobApplications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Surname', models.CharField(max_length=50)),
                ('Gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('PhoneNumber', models.CharField(max_length=20)),
                ('pPosition', models.CharField(max_length=50)),
                ('DOB', models.DateField(verbose_name='Date of Birth')),
                ('Marital_Status', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Divoced', 'Divoced')], max_length=20)),
                ('Email', models.EmailField(max_length=254)),
                ('Address', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'staff_job_application',
            },
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=50)),
                ('receiver', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('date_sent', models.DateTimeField(auto_now_add=True)),
                ('read', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Messages',
            },
        ),
        migrations.CreateModel(
            name='Notices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('Username', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Notices',
            },
        ),
        migrations.CreateModel(
            name='Parents',
            fields=[
                ('Username', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('Name', models.CharField(max_length=100)),
                ('Surname', models.CharField(max_length=100)),
                ('ID_Number', models.CharField(max_length=20, unique=True)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Relationship', models.CharField(max_length=20)),
                ('Phone_Number', models.CharField(max_length=20, unique=True)),
                ('Address', models.CharField(blank=True, max_length=100, null=True)),
                ('Occupation', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'Parents',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('Username', models.CharField(max_length=50, unique=True)),
                ('Name', models.CharField(max_length=50)),
                ('Surname', models.CharField(max_length=50)),
                ('Gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('Position', models.CharField(max_length=50)),
                ('DOB', models.DateField(verbose_name='Date of Birth')),
                ('Marital_Status', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Divoced', 'Divoced')], max_length=20)),
                ('Email', models.EmailField(max_length=254, primary_key=True, serialize=False, unique=True)),
                ('PhoneNumber', models.CharField(max_length=20)),
                ('Address', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'Staff',
            },
        ),
        migrations.CreateModel(
            name='StudentsEnrolments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Surname', models.CharField(max_length=50)),
                ('Gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('DOB', models.DateField()),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Phone_Number', models.CharField(max_length=20)),
                ('Grade_Level', models.CharField(choices=[('ECD A', 'ECD A'), ('ECD B', 'ECD B'), ('Grade 1', 'Grade 1'), ('Grade 2', 'Grade 2'), ('Grade 3', 'Grade 3'), ('Grade 4', 'Grade 4'), ('Grade 5', 'Grade 5'), ('Grade 6', 'Grade 6'), ('Grade 7', 'Grade 7')], max_length=20)),
                ('Address', models.CharField(max_length=100)),
                ('Parent_Name', models.CharField(max_length=100)),
                ('Parent_Surname', models.CharField(max_length=100)),
                ('Parent_Email', models.EmailField(max_length=254)),
                ('Relationship', models.CharField(max_length=20)),
                ('Parent_Phone_Number', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'students_enrolments',
            },
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('Username', models.CharField(editable=False, max_length=8, primary_key=True, serialize=False, unique=True)),
                ('Name', models.CharField(max_length=50)),
                ('Surname', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=6)),
                ('dob', models.DateField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Teachers',
            },
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('RegNumber', models.CharField(editable=False, max_length=8, primary_key=True, serialize=False, unique=True)),
                ('Name', models.CharField(max_length=50)),
                ('Surname', models.CharField(max_length=50)),
                ('Gender', models.CharField(max_length=6)),
                ('DOB', models.DateField()),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Phone_Number', models.CharField(max_length=20)),
                ('Grade_Level', models.CharField(max_length=20)),
                ('Address', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='user_images')),
                ('Parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.parents')),
            ],
            options={
                'db_table': 'Students',
            },
        ),
        migrations.CreateModel(
            name='StudentAttendances',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('present', models.BooleanField(default=False)),
                ('notes', models.CharField(blank=True, max_length=200, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.students')),
            ],
            options={
                'db_table': 'StudentAttendances',
            },
        ),
        migrations.CreateModel(
            name='StaffAttendances',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('present', models.BooleanField(default=False)),
                ('notes', models.CharField(blank=True, max_length=200, null=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.staff')),
            ],
            options={
                'db_table': 'StaffAttendances',
            },
        ),
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=20)),
                ('grade', models.CharField(max_length=2)),
                ('term', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
                ('notes', models.CharField(blank=True, max_length=200, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.students')),
            ],
            options={
                'db_table': 'Results',
            },
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField()),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(max_length=20)),
                ('payment_reason', models.CharField(max_length=200)),
                ('fee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.fees')),
            ],
            options={
                'db_table': 'Payments',
            },
        ),
        migrations.AddField(
            model_name='parents',
            name='Student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.students'),
        ),
        migrations.AddField(
            model_name='fees',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.students'),
        ),
        migrations.CreateModel(
            name='Classrooms',
            fields=[
                ('room_number', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('capacity', models.IntegerField()),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.teachers')),
            ],
            options={
                'db_table': 'Classrooms',
            },
        ),
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_level', models.CharField(max_length=20)),
                ('class_name', models.CharField(max_length=20)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.students')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.teachers')),
            ],
            options={
                'db_table': 'Classes',
            },
        ),
        migrations.CreateModel(
            name='ClassAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('term', models.CharField(max_length=20)),
                ('class_name', models.CharField(max_length=20)),
                ('room_number', models.CharField(max_length=10)),
                ('students', models.ManyToManyField(to='backend.Students')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.teachers')),
            ],
            options={
                'db_table': 'ClassAllocation',
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('present', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.students')),
            ],
            options={
                'db_table': 'Attendance',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(max_length=150, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('role', models.CharField(max_length=50)),
                ('is_online', models.BooleanField(default=False)),
                ('last_logout', models.DateTimeField(blank=True, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('settings', models.TextField(blank=True, null=True)),
                ('verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'auth_user',
                'auto_created': False,
            },
            managers=[
                ('objects', backend.models.CustomUserManager()),
            ],
        ),
    ]
